### ISSUE TITLE
The requested URL returned error: 403

### ISSUE THREAD

**Issue by ehsan5505** [mohammadrajabraza/class-codes-piaic-q3#5]
@mohammadrajabraza 

I'm getting 403 error while uploading the branch on your repo, it seems you are the only person that could manage the upload till we are contributor been allowed or fork the repo

Error Stack
-----
PS \PIAIC_Q3\class-codes-piaic-q3> git push origin assign1/ehsan.rafeeque-PIAIC113318
**remote: Permission to mohammadrajabraza/class-codes-piaic-q3.git denied to ehsan5505.
fatal: unable to access 'https://github.com/mohammadrajabraza/class-codes-piaic-q3.git/': The requested URL returned error: 403**
------

Meanwhile, you can review the code from my github repo, i try to use a new one for this purpose

https://github.com/ehsan5505/PIAIC_Q3

Thanks in advance

**Comment by mohammadrajabraza** [comment]
@ehsan5505 regret for the inconvenience I thought being a public/unrestricted repository it will work that way I told. Please follow [https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/]() for you **PR**. For the time being I'am reviewing code from your repo.

**Comment by YAHYA-YOUNAS** [comment]
Sir, I followed each step mentioned in the blog and after running this:
$ git pull upstream main && git push origin main
I still face that 403 error, kindly tell me what to do now. 
**NOTE: I think you have not given permission to anyone to make a pull request, that's why its permission was denied. Kindly check it out.**
